@baseUrl = http://localhost:8080

### 1) CREATE ACTOR
POST {{baseUrl}}/actor
Content-Type: application/json

{
  "name": "forklift-01",
  "size": 2,
  "enabled": true
}

> {%
  client.global.set("actorId", response.body.id);
%}

### 2) READ ALL
GET {{baseUrl}}/actor
Accept: application/json

### 3) READ ONE
GET {{baseUrl}}/actor/{{actorId}}
Accept: application/json

### 4) UPDATE ACTOR
PUT {{baseUrl}}/actor/{{actorId}}
Content-Type: application/json

{
  "name": "forklift-01-updated",
  "size": 3,
  "enabled": true
}

### 5) READ UPDATED ACTOR
GET {{baseUrl}}/actor/{{actorId}}
Accept: application/json

### 6) DELETE ACTOR
DELETE {{baseUrl}}/actor/{{actorId}}

### 7) READ DELETED ACTOR (EXPECT 404)
GET {{baseUrl}}/actor/{{actorId}}
Accept: application/json
