@baseUrl = http://localhost:8080

### 1) CREATE MAP
POST {{baseUrl}}/map
Content-Type: application/json

{
  "name": "Area Test Map"
}

> {%
  client.global.set("mapId", response.body.id);
%}

### 2) CREATE AREA
POST {{baseUrl}}/map/{{mapId}}/areas
Content-Type: application/json

{
  "name": "ER Zone",
  "type": "DANGER",
  "verticesJson": "[[0,0],[120,0],[120,80],[0,80]]",
  "metadataJson": "{\"riskLevel\":\"HIGH\",\"access\":\"STAFF_ONLY\"}"
}

> {%
  client.global.set("areaId", response.body.id);
%}

### 3) READ AREAS
GET {{baseUrl}}/map/{{mapId}}/areas
Accept: application/json

### 4) READ AREA ONE
GET {{baseUrl}}/map/{{mapId}}/areas/{{areaId}}
Accept: application/json

### 5) UPDATE AREA
PUT {{baseUrl}}/map/{{mapId}}/areas/{{areaId}}
Content-Type: application/json

{
  "name": "ER Zone Updated",
  "type": "CONTROLLED",
  "verticesJson": "[[10,10],[140,10],[140,90],[10,90]]",
  "metadataJson": "{\"riskLevel\":\"MEDIUM\",\"access\":\"LIMITED\"}"
}

### 6) READ UPDATED AREA
GET {{baseUrl}}/map/{{mapId}}/areas/{{areaId}}
Accept: application/json

### 7) DELETE AREA
DELETE {{baseUrl}}/map/{{mapId}}/areas/{{areaId}}

### 8) READ DELETED AREA (EXPECT 404)
GET {{baseUrl}}/map/{{mapId}}/areas/{{areaId}}
Accept: application/json

### 9) DELETE MAP
DELETE {{baseUrl}}/map/{{mapId}}
