@baseUrl = http://localhost:8080

### 1) CREATE MAP
POST {{baseUrl}}/map
Content-Type: application/json

{
  "name": "World Controller Test Map"
}

> {%
  client.global.set("mapId", response.body.id);
%}

### 2) UPLOAD SENSOR MAP (multipart)
POST {{baseUrl}}/map/{{mapId}}/sensor-map
Content-Type: multipart/form-data; boundary=WorldBoundary

--WorldBoundary
Content-Disposition: form-data; name="file"; filename="hospital_refined_map.png"
Content-Type: image/png

< ../hospital_refined_map.png
--WorldBoundary--

### 3) BUILD GRID MAP (WorldController)
POST {{baseUrl}}/map/{{mapId}}/keepout-zones
Content-Type: application/json

{
  "name": "World Keepout Zone",
  "verticesJson": "[[0,0],[1000,0],[1000,300],[0,300]]",
  "enabled": true,
  "reason": "world.http keepout test"
}

> {%
  client.global.set("keepoutId", response.body.id);
%}

### 4) BUILD GRID MAP (WITH ENABLED KEEPOUT)
POST {{baseUrl}}/world/{{mapId}}/build
Accept: application/json

### 5) DISABLE KEEPOUT ZONE
PUT {{baseUrl}}/map/{{mapId}}/keepout-zones/{{keepoutId}}
Content-Type: application/json

{
  "name": "World Keepout Zone",
  "verticesJson": "[[0,0],[1000,0],[1000,300],[0,300]]",
  "enabled": false,
  "reason": "disable keepout in world.http"
}

### 6) BUILD GRID MAP (WITH DISABLED KEEPOUT)
POST {{baseUrl}}/world/{{mapId}}/build
Accept: application/json

### 7) GET CACHED GRID MAP IMAGE (PNG)
GET {{baseUrl}}/world/{{mapId}}/image
Accept: image/png

### 8) BUILD WITH INVALID MAP ID (EXPECT 404)
POST {{baseUrl}}/world/999999999/build
Accept: application/json

### 9) DELETE MAP
DELETE {{baseUrl}}/map/{{mapId}}
